test: &default
  client_id: Af9VSxCd5wxQdClB8LhhU0TO-5uWQMKSNMRf1RvaPSl5tIHzQouBULbBdlWR
  client_secret: EGWyVRD8DBg4OfWdI-MjI7G2WcFvUcRLpwPBgV9N7mhJsHbr8iy68Kuuz-03
  mode: sandbox
  sandbox_email_address: andey-facilitator@ymail.com

development:
  <<: *default

production:
  <<: *default
  #mode: live
