test: &default

  # Credentials for REST APIs
  client_id: Af9VSxCd5wxQdClB8LhhU0TO-5uWQMKSNMRf1RvaPSl5tIHzQouBULbBdlWR
  client_secret: EGWyVRD8DBg4OfWdI-MjI7G2WcFvUcRLpwPBgV9N7mhJsHbr8iy68Kuuz-03

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: andey-facilitator@ymail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
